# Navie Bayes Algorithm (NB)
- simple but surprisinly powerful alogrithm for predictive modeling and machine learning.
- based on bayes therom
- particularly useful in the classification taks.
- text classification tasks such spam filtering and sentiment analysis 
### Navie Bayes Alogrithm (NB)
Navie bayes is a  probabilistic machine learning model that is used for classification tasks.\
it is based on the bayes therom which describe the probability of an event on the prior knowledge of conditions related to the event.\
The navie aspect's of algortim comes from the facts that features that used to predict the target variable and indepedent of each other.
### Bayes Therom (BT)
At it's core bayes therom provides a way to calculate the probability of an hypothesis based the prior knowledge.Mathmatically, it's expressed as 
 P(A|B)= P(B|A)*P(A)/P(B)\
 where:P(A|B) is the probability of hypothesis A given by the data B.\
 P(A|B) is the probability of data B given that hypothesis A is correct.\
 P(A) is the probability of hypothesis A begin ture (regardless of the given data B)\
 P(B) is the probability of Data B (regardless of the hypothesis A)
 ## Types of Naive Bayes classifier 
 ### 1. Gussian Navie Bayes:
 Used When features are contionus and normaly distributed
 ### 2. Multinominal Navie Bayes
 Often used for document classification. Where the features are the frequenices of the words or tokens in the documents.
 ### Bernouli Navie Bayes:
 Used when features are binary(0s and 1s)

 ## Application of Navie Bayes
 - Email spam filtering 
 - Sentiment analysis
 - Docutment Categorization
 - Medical Diagonsis
 ## Advantages of Navie Bayes
 - **Simplicity**: They are straightforward to implement and understand 
 - **Efficiency**: Require small amount of a training data to estimate the necessay parameters.
 - **Speed**: Very fast, making them suitable for real time predications.
 - **Good performance**: Often perform well in mutli-class predication
 ## Disadvantages of Navie Bayes:
 1. **Feature Independence:**  The assumption is a independent features is the strong one and not applicable in some cases.
 2. **Data Scarcity:** If the categorical data has category in testing data set, which model haven't seen in the traning data. The model wil assign the zero probability to it and will not be able to make prediction. This is often knows as **Zero Frequency**
 3. **Highly Corelated features** The Model will not perform well when the feature are highly corelated.

In [2]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns
from sklearn.naive_bayes import GaussianNB,MultinomialNB,BernoulliNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.datasets import load_iris
# split the data into x and y 
iris= load_iris()
x = iris.data 
  
y = iris.target
# split the data into traning and testing data 
x_train,x_test,y_train,y_test= train_test_split(x,y,test_size=0.2,random_state=21)
Gnb= GaussianNB()
# fit the model 
Gnb.fit(x_train,y_train)
# predict from the model
y_pred= Gnb.predict(x_test)
# Evaluate the Model
print("Classification Report:\n", classification_report(y_test,y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test,y_pred))

Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        11
           1       1.00      0.92      0.96        12
           2       0.88      1.00      0.93         7

    accuracy                           0.97        30
   macro avg       0.96      0.97      0.96        30
weighted avg       0.97      0.97      0.97        30

Confusion Matrix:
 [[11  0  0]
 [ 0 11  1]
 [ 0  0  7]]


In [5]:
# Mulitnominal algorithm
Mnb= MultinomialNB()
Mnb.fit(x_train,y_train)
y_pred=Mnb.predict(x_test)
print("Classification Report\n",classification_report(y_test,y_pred))
print("Confusion Matrix:\n",confusion_matrix(y_test,y_pred))

Classification Report
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        11
           1       1.00      0.33      0.50        12
           2       0.47      1.00      0.64         7

    accuracy                           0.73        30
   macro avg       0.82      0.78      0.71        30
weighted avg       0.88      0.73      0.72        30

Confusion Matrix:
 [[11  0  0]
 [ 0  4  8]
 [ 0  0  7]]


In [7]:
Bnb = BernoulliNB()
Bnb.fit(x_train,y_train)
y_pred = Bnb.predict(x_test)
print("Classification Report\n",classification_report(y_test,y_pred))
print("Confusion Matrix:\n",confusion_matrix(y_test,y_pred))

Classification Report
               precision    recall  f1-score   support

           0       0.00      0.00      0.00        11
           1       0.00      0.00      0.00        12
           2       0.23      1.00      0.38         7

    accuracy                           0.23        30
   macro avg       0.08      0.33      0.13        30
weighted avg       0.05      0.23      0.09        30

Confusion Matrix:
 [[ 0  0 11]
 [ 0  0 12]
 [ 0  0  7]]


c:\Users\Basit\miniconda3\envs\python_ml\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\Basit\miniconda3\envs\python_ml\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\Basit\miniconda3\envs\python_ml\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
